language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=origin/2.1
    - SYMFONY_VERSION=origin/2.2
    - SYMFONY_VERSION=origin/2.3

before_script:
    - composer self-update 
    - composer install --dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4235a4d7b989b3e1ac53
    on_success: change
    on_failure: always
    on_start: false
